# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: build x86
      run: msbuild /restore src\TreeDumpLibrary\TreeDumpLibrary.csproj /p:platform=x86 /p:configuration=release

    - name: build x64
      run: msbuild /restore src\TreeDumpLibrary\TreeDumpLibrary.csproj /p:platform=x64 /p:configuration=release

    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1

    - name: pack
      run: nuget pack src\TreeDumpLibrary\TreeDumpLibrary.nuspec

    - name: build x86
      run: msbuild /restore src\XamlTreeDump.sln /p:platform=x86 /p:configuration=debug

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: test
      run: vstest.console.exe /platform:x86 src\UnitTests\bin\x86\Debug\UnitTests.build.appxrecipe
